branches:
  only:
    - gh-pages

language: ruby

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

before_install: 
  - gem install bundler
  - bundle install

script: bundle exec jekyll build
