title: NuPIC
tagline: Numenta&nbsp;Platform&nbsp;for Intelligent&nbsp;Computing

baseurl: http://rhyolight.github.io/numenta.org/

future: false

markdown: maruku

name: NuPIC
description: Numenta Platform for Intelligent Computing

exclude: [vendor]

safe: true
lsi: false
pygments: true
source: .
