title: NuPIC
tagline: Numenta&nbsp;Platform&nbsp;for Intelligent&nbsp;Computing

baseurl: http://numenta.org

future: false

markdown: Kramdown

name: NuPIC
description: Numenta Platform for Intelligent Computing

exclude: [vendor]

safe: true
lsi: false
highlighter: pygments
source: .

gems:
  - jekyll-redirect-from

