# Numenta.org Jekyll Config
# http://jekyllrb.com/docs/configuration/

### about

description:  Numenta Platform for Intelligent Computing
#github:      # gh-pages add
name:         NuPIC
tagline:      Numenta Platform for Intelligent Computing
title:        NuPIC

### paths

data_source:  ./_data
destination:  ./_site
#include_dir: ./_includes # jekyll lock
layouts:      ./_layouts
plugins:      ./_plugins
sass_dir:     ./_sass
source:       . # gh-pages lock

### settings

encoding:     utf-8
future:       false
gems:         [ 'jekyll-redirect-from' ]
highlighter:  pygments
lsi:          false # gh-pages lock
markdown:     kramdown
safe:         true # gh-pages lock
timezone:     America/Los_Angeles

### inclusions/exclusions

#include:
exclude:
  - _config.yml
  - CNAME
  - Gemfile
  - Gemfile.lock
  - npm-debug.log
  - package.json
  - README.md
  - _data/
  - _includes/
  - _layouts/
  - _sass/
  - _site/
  - node_modules/kss/

### plugins

kramdown:
  input: GFM # github-flavored markdown

### defaults

# defaults:
#   -
#     scope:
#       path: '' # all files
#       type: 'posts'
#     values:
#       layout: 'default'
#   -
#     scope:
#       path: 'projects'
#       type: 'pages'
#     values:
#       layout: 'project'
#       author: 'Vito'

### collections http://jekyllrb.com/docs/collections/

# collections:

